apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          env:
            - name: APP_PORT
              value: "8888"
            - name: APP_OUTPUT_FILE
              value: "/var/app/data/pingpong.txt"
            - name: APP_LOG_FILE
              value: "pingpong.log"
          image: pasiol/ping-pong@sha256:357daceabd8131247e4596e354856de6327f40b46390d5ba89d8a33922670cbe
          imagePullPolicy: IfNotPresent