apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: ping-pong
          env:
            - name: APP_PORT
              value: "8888"
            - name: APP_OUTPUT_FILE
              value: "/var/app/data/pingpong.txt"
            - name: APP_LOG_FILE
              value: "pingpong.log"
          image: pasiol/ping-pong@sha256:c2ae30be6702a1399812678436c31da5f1095155e55a4fcb0f65db2c96fa1fae