apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          env:
            - name: APP_PORT
              value: "8888"
            - name: ALLOWED_ORIGINS
              value: ping-pong-svc
            - name: POSTGRES_HOST
              value: ping-pong-postgres-svc
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
          image: pasiol/ping-pong@sha256:fe9b619eecdedb196b956594863ddc069cca48f7f46f7246e3983c195d3c93c2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "50m"
              memory: "10Mi"