apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: applications
data:
    POSTGRES_USER: ENC[AES256_GCM,data:P83P6/wnY79ZzekTg38qMA==,iv:so83tkUlqoL3wD42MG4TGUgFVAMAVL4HGJCl8Q/V80Q=,tag:+5Ejhgg9rl8XtJQAxESfYw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0Ktdl5CeMbQmeMXaKqLk62uzLQA=,iv:8kqtWddiHboJiyiL1/MFcVIgJalNjJjPAWJhEzYwrVU=,tag:rKSHTFbaAvo/Mf7K07q5AA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:dzX7vU+VxUWpQymDZCZLyF1HB+k=,iv:BR6YlHcDZymlUfipLM09FpWycw5+5QrTdHdZrSYF5iM=,tag:2/THz/Wh8OQzKNuHuoKmDw==,type:str]
immutable: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kdhxyxzul9q095wq9rc3hfkc4ukt2yze2474f46pk84wl5c7l4kqlxurfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd3NzTHVPRXNPeG81bXBD
            aXZMZ0J4RU9ocGZ6WXh5MjVzOVY1R1ZtWUc0ClhmckdoR1lUQ2xVVHdDUXNRNVRr
            NlE4SHpucWJnZHpBRUQ3My9xSlMxSWMKLS0tIEgyQk1tYk96UXNnSmFSVDh5dG9q
            dXREQWpxL0Q4UVc1NXlhMHFDVXVXWjAKjy9NiEWJUEShsvdP4tCu31jSLuu7VfWp
            RoYycNQUpcj2YG4jyowv53xpJGHPa6oH7iY16zseFZSiJf5ioKYFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-20T15:32:17Z"
    mac: ENC[AES256_GCM,data:9/VZgBEAHh64fMluS3NqzTRYN/TvCAUSg220c8BbCmWi9ro770RPHoSbF39EBdod1DztXeU6EWWA9nubOY2yFsUPkOC8phLspJjwxOiTW5Akiv+LhcOUtydAVmK/Ov9qg9u23D3ZmzdLNFHrTBMZZZC9FpDytzWBiq4L9YgGq3w=,iv:x2XKcM+F11bDcZ225/eSAhm1WWovFyunVtKyqcZpKjc=,tag:CKPI18VNuT0dC+mqwVp58g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
