apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-postgres
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-postgres
  template:
    metadata:
      labels:
        app: ping-pong-postgres
    spec:
      containers:
        - name: postgres-pingpong
          image: pasiol/postgres@sha256:bfc952e11e0202b0a55860d07b202f969da426b1447b0da21a5efdc65ea90a9f
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: pingpong-pvc