apiVersion: v1
kind: Service
metadata:
  name: ping-pong-postgres-svc
  namespace: applications
spec:
  type: ClusterIP
  selector:
    app: ping-pong-postgres
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432